### ISSUE TITLE
Send help, getting money is hard.

### ISSUE THREAD

**Issue by Eperos** [ConfederationC/Learning#11]
Getting money always seems to require doing "work". Someone please fix this.

**Comment by owlsnowy** [comment]
yep it certainly is

**Comment by Zurasa** [comment]
Ill look into the patch notes, maybe there's an article about passive farming somewhere.

**Comment by QueenAlloy** [comment]
This seems like a pretty big issue, have you tried dying your hair, starting a blog, and opening a Patreon account?

**Comment by Eperos** [comment]
That response has triggered my ptsd, i'll be contacting your employer.

**Comment by Eperos** [comment]
Found money. Need to lay low for a bit, closing issue to hide evidence.
