### ISSUE TITLE
Help needed adding labels to issues like this one

### ISSUE THREAD

**Issue by F1xx** [ConfederationC/Learning#13]
yeah labels are not able to be added unless I am missing something
Halp @applecheeks37

**Comment by applecheeks37** [comment]
I am here to help! Step one: pour milk onto computer. Let me know what happens.

**Comment by mGigs** [comment]
same I do not see any labels

**Comment by F1xx** [comment]
It worked!  The label grew from the Hard Drive with beefy, strong-boned arms!
Also a gear showed up, I assume permissions changed.  So now just go to the right menu and click the gear next to Labels
