### ISSUE TITLE
Why my iphone4s often restart automatically?

### ISSUE THREAD

**Issue by mzheng3004** [ConfederationC/Learning#16]
My iphone4s often restart automatically when I watch video online. How to fix it?

**Comment by stomas96** [comment]
get matt carr to fix your iphone or restore your iphone on itunes.

**Comment by mzheng3004** [comment]
Thanks for your help.

**Comment by mzheng3004** [comment]
Problem fixed and close the issue

**Comment by mzheng3004** [comment]
Already fixed
