### ISSUE TITLE
Labels?

### ISSUE THREAD

**Issue by Eperos** [ConfederationC/Learning#16]
Adding labels is hard, please help.

**Comment by gloomygalleon** [comment]
is your refrigerator running

**Comment by JReszitnyk** [comment]
I'm having a problem with labeling too.

**Comment by Eperos** [comment]
Can't afford one, all I've got is this cardboard box full of snow.

**Comment by KaukinenConfed** [comment]
Eperos ... you have been added, try again

**Comment by KaukinenConfed** [comment]
JReszitnyk - you have been added. try again
