### ISSUE TITLE
Low laptop battery 

### ISSUE THREAD

**Issue by stomas96** [ConfederationC/Learning#17]
my laptop battery has become low, how do I fix this?

**Comment by chyslop1** [comment]
place your laptop in the oven at 400 degrees Celsius and bake fore 3 hours. Your battery should be fully charged then!

**Comment by mzheng3004** [comment]
Keep your cable plugging in all the time or change a new battery for your laptop.

**Comment by stomas96** [comment]
thank you all, i appreciate all the help!
