### ISSUE TITLE
Processor problem!

### ISSUE THREAD

**Issue by bwillson1** [ConfederationC/Learning#19]
Hi, I added thermal paste to my processor but it seems to be overheating! What did I do wrong?

![](http://i.imgur.com/KSWVpDQ.jpg)

**Comment by DanRosborough** [comment]
You need more RAM

**Comment by bwillson1** [comment]
Wow that fixed it! All I had to do was download more ram 💯

**Comment by KaukinenConfed** [comment]
Ok, try now. Please close this issue if you problem has been resolved
