### ISSUE TITLE
How do what do?

### ISSUE THREAD

**Issue by devonryder** [ConfederationC/Learning#20]
How do I use the stuff in here? It doesn't work. Halp!!!!!

**Comment by vortex1409** [comment]
Do what how

**Comment by devonryder** [comment]
Things and stuff how do

**Comment by DavidAskwith** [comment]
not to sure. I guess I'm not to helpful

**Comment by JMarkus9** [comment]
Click buttons and hope for the best.

**Comment by devonryder** [comment]
I can now do...thanks santa!!!!
