### ISSUE TITLE
Zurasa cannot add labels

### ISSUE THREAD

**Issue by Zurasa** [ConfederationC/Learning#22]
This user: Zurasa cannot add labels to issues or pull requests
Please grant access

**Comment by MattStewardson** [comment]
Well did you try turning it off and on again?

**Comment by jestrell** [comment]
do you have access to internet ?

**Comment by Zurasa** [comment]
ahh my router is down, no wonder i cant label my issue

**Comment by Zurasa** [comment]
It worked! Thanks for the help

**Comment by KaukinenConfed** [comment]
Ok, try now. Please close this issue if you problem has been resolved
oops... here is the enter for post
