### ISSUE TITLE
Twitch Intergration Problems

### ISSUE THREAD

**Issue by Jkarat** [ConfederationC/Learning#29]
I am having trouble connecting my GitHub and Twitch account so that I can stream my repository.

**Comment by chyslop1** [comment]
you will need to call the head of Twich and he will give you the backdoor code over the phone.

**Comment by Commandori** [comment]
get good you casual

**Comment by bwillson1** [comment]
You need the dank memes extension in order for them to connect

**Comment by Jkarat** [comment]
Thanks for the help.
