### ISSUE TITLE
Can't Label

### ISSUE THREAD

**Issue by KeanConfed** [ConfederationC/Learning#44]
Cant seem to label.  Help please

**Comment by KaukinenConfed** [comment]
@gloomygalleon please take care of this

**Comment by KeanConfed** [comment]
Thank you for adding the label.

**Comment by gloomygalleon** [comment]
Take care! Bon Voyage!

**Comment by KaukinenConfed** [comment]
@gloomygalleon Could you add KeanConfed to the team?

**Comment by gloomygalleon** [comment]
Cannot!

**Comment by KaukinenConfed** [comment]
Sent you a join request in email. please accept

**Comment by KaukinenConfed** [comment]
please close the issue, steve, when you have it all resolved
