### ISSUE TITLE
Sidewalk Issue!

### ISSUE THREAD

**Issue by gloomygalleon** [ConfederationC/Learning#5]
Hey! It's icy on some of the sidewalks! Can you "**pls fix thx**" this issue? Thanks!

**Comment by Eperos** [comment]
Have you tried turning it off and on again?

**Comment by gloomygalleon** [comment]
Wow! I tried doing that and they all exploded! Thank you very much for your help!

**Comment by Eperos** [comment]
Exploded sidewalk proving problematic for getting around.

**Comment by gloomygalleon** [comment]
we're all going to die in the end, it's ok
