### ISSUE TITLE
Help needed for new print feature

### ISSUE THREAD

**Issue by applecheeks37** [ConfederationC/Learning#7]
New print feature is becoming a pain. Need someone else to help.

**Comment by F1xx** [comment]
What you need to do is not mess up and then it will print.

**Comment by applecheeks37** [comment]
Thanks! That was the issue!

**Comment by applecheeks37** [comment]
Complete comments, thanks to @F1xx

**Comment by applecheeks37** [comment]
Added label to this, now am going to close.

**Comment by applecheeks37** [comment]
Complete.

**Comment by F1xx** [comment]
YOUR WORK IS NEVER COMPLETE
Re-opened

**Comment by applecheeks37** [comment]
Son of a gun! IT IS NOW COMPLETE

**Comment by F1xx** [comment]
I'm still not convinced this is complete

**Comment by applecheeks37** [comment]
It is complete. Forever and always.
